# .travis.yml
language: node_js

node_js:
  - '0.10'

before_script:
  - ./node_modules/knex/lib/bin/cli.js migrate:latest --knexfile ./test/knexfile.js

script: "npm run-script test-travis"

after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"

notifications:
  email: false
